# Generated by Django 4.1.1 on 2022-11-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lnmo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name'], name='edu_lnmo_us_last_na_08bd11_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='edu_lnmo_us_first_n_f13808_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['middle_name'], name='edu_lnmo_us_middle__69beaf_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['birth_date'], name='edu_lnmo_us_birth_d_19d4a5_idx'),
        ),
    ]
