# Generated by Django 4.1.1 on 2022-11-15 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('edu_lnmo', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('GRP', 'Группа'), ('FRM', 'Форум'), ('SUP', 'Поддержка')], max_length=3)),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название темы')),
                ('support_status', models.CharField(blank=True, choices=[('OPEN', 'Открыт'), ('CLOSED', 'Закрыт'), ('RESOLVED', 'Решен'), ('REJECTED', 'Отклонен'), ('MORE_INFO', 'Требуется уточнение')], max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(max_length=255, verbose_name='Предметная область')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт олимпиады')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место проведения')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_lnmo.department', verbose_name='Организатор')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OlympiadParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата участия')),
                ('award', models.CharField(blank=True, max_length=255, null=True, verbose_name='Награда')),
                ('team_member', models.BooleanField(default=False, verbose_name='В составе команды')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_lnmo.olympiad', verbose_name='Олимпиада')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invert_condition', models.BooleanField(default=False, verbose_name='Инвертировать условие')),
                ('do_allow', models.BooleanField(default=False, verbose_name='Разрешить доступ (или запретить)')),
                ('for_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='Класс')),
                ('role', models.CharField(blank=True, max_length=255, null=True, verbose_name='Роль')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_permissions', to='auth.group', verbose_name='Группа пользователей')),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_permissions', to='edu_lnmo.educationspecialization', verbose_name='Направление обучения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='edu_lnmo.threadgroup', verbose_name='Родительская группа')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='messageprivate',
            name='message_ptr',
        ),
        migrations.RemoveField(
            model_name='messageprivate',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messagetasksubmission',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='messagetasksubmission',
            name='messageprivate_ptr',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='activity',
            name='submittable',
            field=models.BooleanField(default=True, verbose_name='Отправка решений разрешена'),
        ),
        migrations.AddField(
            model_name='message',
            name='manual_audience',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предназначено для ролей'),
        ),
        migrations.AddField(
            model_name='message',
            name='manual_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_received', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('THR', 'Тематическое'), ('PRV', 'Личное'), ('NEW', 'Новость'), ('MAN', 'Справка')], default='PRV', max_length=3),
        ),
        migrations.AlterField(
            model_name='activity',
            name='scientific_topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Научный раздел'),
        ),
        migrations.DeleteModel(
            name='MessageNews',
        ),
        migrations.DeleteModel(
            name='MessagePrivate',
        ),
        migrations.DeleteModel(
            name='MessageTaskSubmission',
        ),
        migrations.AddField(
            model_name='messagethread',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='edu_lnmo.threadgroup', verbose_name='Группа тем'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='edu_lnmo.messagethread', verbose_name='Тема'),
        ),
    ]
