# Generated by Django 4.1.1 on 2022-11-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lnmo', '0004_alter_activity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
    ]
