# Generated by Django 4.1.1 on 2022-12-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lnmo', '0007_alter_activity_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='unreadobject',
            name='created',
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['content_type'], name='edu_lnmo_ac_content_41ca77_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['course'], name='edu_lnmo_ac_course__fce4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['title'], name='edu_lnmo_ac_title_9aba0a_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['keywords'], name='edu_lnmo_ac_keyword_e6dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['lesson_type'], name='edu_lnmo_ac_lesson__8f5973_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_hidden'], name='edu_lnmo_ac_is_hidd_04e776_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['hours'], name='edu_lnmo_ac_hours_5e56ec_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['fgos_complient'], name='edu_lnmo_ac_fgos_co_b82de2_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['order'], name='edu_lnmo_ac_order_f7bb2d_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['date'], name='edu_lnmo_ac_date_ead6af_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['group'], name='edu_lnmo_ac_group_3b7e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['scientific_topic'], name='edu_lnmo_ac_scienti_80a405_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['due_date'], name='edu_lnmo_ac_due_dat_d033e3_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['submittable'], name='edu_lnmo_ac_submitt_6b6bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['embed'], name='edu_lnmo_ac_embed_822adb_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['type'], name='edu_lnmo_co_type_bf72e5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='edu_lnmo_co_title_1d010d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['for_class'], name='edu_lnmo_co_for_cla_3a5a79_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['for_specialization'], name='edu_lnmo_co_for_spe_1d5923_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['for_group'], name='edu_lnmo_co_for_gro_614a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['logo'], name='edu_lnmo_co_logo_id_a7b81c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['cover'], name='edu_lnmo_co_cover_i_03486a_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['person'], name='edu_lnmo_co_person__df438b_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course'], name='edu_lnmo_co_course__049e50_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['role'], name='edu_lnmo_co_role_f79a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['finished_on'], name='edu_lnmo_co_finishe_1ba5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization'], name='edu_lnmo_de_organiz_233c43_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='edu_lnmo_de_name_057ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['student'], name='edu_lnmo_ed_student_422577_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['started'], name='edu_lnmo_ed_started_772f73_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['finished'], name='edu_lnmo_ed_finishe_b9f3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['starting_class'], name='edu_lnmo_ed_startin_33f3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['finishing_class'], name='edu_lnmo_ed_finishi_d89705_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['specialization'], name='edu_lnmo_ed_special_4b2377_idx'),
        ),
        migrations.AddIndex(
            model_name='educationspecialization',
            index=models.Index(fields=['name'], name='edu_lnmo_ed_name_83786d_idx'),
        ),
        migrations.AddIndex(
            model_name='educationspecialization',
            index=models.Index(fields=['department'], name='edu_lnmo_ed_departm_377b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['name'], name='edu_lnmo_fi_name_7ed015_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['hash'], name='edu_lnmo_fi_hash_a36b13_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['size'], name='edu_lnmo_fi_size_72801c_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['mime_type'], name='edu_lnmo_fi_mime_ty_cb7f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['author'], name='edu_lnmo_ma_author__a6631f_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['student'], name='edu_lnmo_ma_student_054489_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['value'], name='edu_lnmo_ma_value_32ef66_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['activity'], name='edu_lnmo_ma_activit_02b470_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['type'], name='edu_lnmo_me_type_af6aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread'], name='edu_lnmo_me_thread__b9c08e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='edu_lnmo_me_sender__a9254f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver'], name='edu_lnmo_me_receive_6536cd_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['manual_category'], name='edu_lnmo_me_manual__b0c301_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['manual_audience'], name='edu_lnmo_me_manual__b09bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['type'], name='edu_lnmo_me_type_9cfb64_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['topic'], name='edu_lnmo_me_topic_aec425_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['support_status'], name='edu_lnmo_me_support_ec86cd_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['group'], name='edu_lnmo_me_group_i_e4740c_idx'),
        ),
        migrations.AddIndex(
            model_name='multitoken',
            index=models.Index(fields=['user'], name='edu_lnmo_mu_user_id_efbe06_idx'),
        ),
        migrations.AddIndex(
            model_name='multitoken',
            index=models.Index(fields=['key'], name='edu_lnmo_mu_key_692e75_idx'),
        ),
        migrations.AddIndex(
            model_name='multitoken',
            index=models.Index(fields=['created'], name='edu_lnmo_mu_created_923a83_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiad',
            index=models.Index(fields=['name'], name='edu_lnmo_ol_name_a53914_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiad',
            index=models.Index(fields=['category'], name='edu_lnmo_ol_categor_0c66ff_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiad',
            index=models.Index(fields=['location'], name='edu_lnmo_ol_locatio_5f06e3_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiad',
            index=models.Index(fields=['department'], name='edu_lnmo_ol_departm_b36762_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiadparticipation',
            index=models.Index(fields=['olympiad'], name='edu_lnmo_ol_olympia_45a088_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiadparticipation',
            index=models.Index(fields=['person'], name='edu_lnmo_ol_person__2401eb_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiadparticipation',
            index=models.Index(fields=['date'], name='edu_lnmo_ol_date_2c8e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiadparticipation',
            index=models.Index(fields=['award'], name='edu_lnmo_ol_award_74fdcb_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiadparticipation',
            index=models.Index(fields=['team_member'], name='edu_lnmo_ol_team_me_de76ed_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='edu_lnmo_or_name_9f1a86_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name_short'], name='edu_lnmo_or_name_sh_ab4ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['invert_condition'], name='edu_lnmo_pe_invert__72256c_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['do_allow'], name='edu_lnmo_pe_do_allo_1590e2_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['user'], name='edu_lnmo_pe_user_id_38db41_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['group'], name='edu_lnmo_pe_group_i_27a158_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['for_class'], name='edu_lnmo_pe_for_cla_48b5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['spec'], name='edu_lnmo_pe_spec_id_d0fe94_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['role'], name='edu_lnmo_pe_role_63be7e_idx'),
        ),
        migrations.AddIndex(
            model_name='threadgroup',
            index=models.Index(fields=['name'], name='edu_lnmo_th_name_013f14_idx'),
        ),
        migrations.AddIndex(
            model_name='threadgroup',
            index=models.Index(fields=['parent'], name='edu_lnmo_th_parent__9d2962_idx'),
        ),
        migrations.AddIndex(
            model_name='unreadobject',
            index=models.Index(fields=['obj'], name='edu_lnmo_un_obj_3f3534_idx'),
        ),
        migrations.AddIndex(
            model_name='unreadobject',
            index=models.Index(fields=['type'], name='edu_lnmo_un_type_d1434b_idx'),
        ),
        migrations.AddIndex(
            model_name='unreadobject',
            index=models.Index(fields=['user'], name='edu_lnmo_un_user_id_4a9855_idx'),
        ),
    ]
