# Generated by Django 4.1.1 on 2022-12-06 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lnmo', '0008_alter_user_options_remove_unreadobject_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='hours',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='marks_limit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лимит оценок'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер в списке курса'),
        ),
    ]
