# Generated by Django 4.1.1 on 2022-12-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lnmo', '0010_activity_weight'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='olympiad',
            name='edu_lnmo_ol_locatio_5f06e3_idx',
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='location',
        ),
        migrations.AddField(
            model_name='olympiad',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_lnmo.file', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='organization',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='olympiadparticipation',
            name='location',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='olympiadparticipation',
            name='stage',
            field=models.CharField(max_length=255, null=True, verbose_name='Этап олимпиады'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_lnmo.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='olympiadparticipation',
            name='award',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Награда'),
        ),
        migrations.AlterField(
            model_name='olympiadparticipation',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата участия'),
        ),
        migrations.AddIndex(
            model_name='olympiad',
            index=models.Index(fields=['logo'], name='edu_lnmo_ol_logo_id_b61329_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiad',
            index=models.Index(fields=['organization'], name='edu_lnmo_ol_organiz_3a5ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiadparticipation',
            index=models.Index(fields=['stage'], name='edu_lnmo_ol_stage_d6b875_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiadparticipation',
            index=models.Index(fields=['location'], name='edu_lnmo_ol_locatio_977217_idx'),
        ),
    ]
