# Generated by Django 4.1.1 on 2023-01-13 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lnmo', '0011_remove_olympiad_edu_lnmo_ol_locatio_5f06e3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiadparticipation',
            name='olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='edu_lnmo.olympiad', verbose_name='Олимпиада'),
        ),
        migrations.AlterField(
            model_name='olympiadparticipation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiads', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='olympiadparticipation',
            name='stage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Этап олимпиады'),
        ),
    ]
