# Generated by Django 4.1.1 on 2023-04-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lnmo', '0012_alter_olympiadparticipation_olympiad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='role',
            field=models.CharField(choices=[('t', 'Преподаватель'), ('s', 'Учащийся'), ('m', 'Менеджер'), ('o', 'Наблюдатель'), ('l', 'Вольный слушатель')], max_length=3),
        ),
    ]
