# Generated by Django 4.2.3 on 2023-08-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lnmo', '0013_alter_courseenrollment_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archived',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования'),
        ),
        migrations.AddField(
            model_name='course',
            name='marking',
            field=models.CharField(choices=[('NOP', 'Без оценивания'), ('FVE', '5-бальная'), ('HND', '100-бальная'), ('CST', 'Произвольная')], default='FVE', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('GEN', 'Курс'), ('EDU', 'Учебная программа'), ('SEM', 'Семинар'), ('CLB', 'Кружок'), ('ELE', 'Предмет по выбору'), ('ADM', 'Вступительное испытание')], default='GEN', max_length=3),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['marking'], name='edu_lnmo_co_marking_3ef1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['archived'], name='edu_lnmo_co_archive_0e90c3_idx'),
        ),
    ]
