# Generated by Django 4.2.3 on 2023-08-26 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lnmo', '0014_course_archived_course_marking_alter_course_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='edu_lnmo.file', verbose_name='Каталог'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner'], name='edu_lnmo_fi_owner_i_c6a66f_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['parent'], name='edu_lnmo_fi_parent__d9231b_idx'),
        ),
    ]
