# Generated by Django 4.2.3 on 2023-08-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_lnmo', '0015_file_owner_file_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file_quota',
            field=models.IntegerField(blank=True, default=104857600, null=True, verbose_name='Квота на файлы'),
        ),
    ]
